version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the React code...
      - npm run build
      - echo Zipping the build artifacts...
      - cd build
      - zip -r ../build-output.zip .
      - echo Copying the build artifacts to S3...
      - aws s3 cp ../build-output.zip s3://398779562917-deployment-artifact/

artifacts:
  files:
    - 'build-output.zip'
